### ISSUE TITLE
Show Github/Status Badges in Analyze Section

### ISSUE THREAD

**Issue by frano-m** [HumanCellAtlas/data-portal#178]
Show CI (build) and code coverage badges on the HCA portal page, and ideally have the ability to click through on the code coverage and CI services badges. Here is an [example](https://github.com/eweitz/ideogram#ideogram) of build and code coverage badges.

Stretch: Show mashup badges on the HCA portal page, and ideally have the ability to click through. The mashup badge would be a custom badge, and it could have just the word "mashup" and link to the corresponding repo. Here is an [example](https://github.com/eweitz/morpheus.js-react).

This work requires a clear document on the design of the badges implementation: how to include markdown, and which repo the markdown should live.

**Comment by NoopDog** [comment]
@vickylihorst can you add a bit of detail or link to the spec that defines which badges you are looking for.

**Comment by NoopDog** [comment]
Hi @vickylihorst can you give an example of each badge type. Want to be sure we get the right ones.

I am not sure what mashup is.
Might be good to look at each portal that we have listed an decide which ones of their badges we want to show.

Is that something that can be done?

Thanks!

**Comment by vickylihorst** [comment]
For build and code coverage services, there are multiple providers, for example, Travis CI and CircleCI are two build service providers. Ultimately, we'd want to support multiple providers for each type of service (e.g. both Travis CI and CircleCI), but for now, only supporting one type would suffice.
